version: "3.9"

services:
  finapi_database:
    image: postgres
    container_name: finapi_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=finapi
      - POSTGRES_PASSWORD=finapi123
      - POSTGRES_DB=finapi_database
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: finapi
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - finapi_database
    depends_on:
      - finapi_database

volumes:
  pgdata:
